### ISSUE TITLE
Logo

### ISSUE THREAD

**Issue by will-stone** [rafamel/themelier#1]
Nice project! Thanks for the nod to [Plastic](https://github.com/will-stone/plastic) and using it in your project. Any chance we could design you a new logo? The current one is obviously taken from Plastic, maybe we could make you your own identity? Maybe start by taking [Plastic's logo](https://github.com/will-stone/plastic/tree/master/images) and changing the colour scheme and go from there. That linked-to folder contains an SVG file if you don't have Affinity Designer.

**Comment by rafamel** [comment]
Hi will, sorry for leaving this open for such a long time. I began development of this extension and eventually abandoned it for lack of time. I'm gonna continue with it now. I did take the general outlook of the Plastic logo as a base and assumed it would be ok, as it was MIT; I should have contacted you first nevertheless. I am not a design person so my design skills are limited to a few modifications on GIMP. Would it be ok with you to leave it as is? Otherwise I'll try to take a different approach.

Thanks,
Rafa.

**Comment by will-stone** [comment]
I'm not a great designer either (all my logos are very simple and flat). However surely you'd like your own identity? Here's something I did with 3 characters and 3 colours in seconds:

![image](https://user-images.githubusercontent.com/654103/33426266-2565f66a-d5b9-11e7-9f87-53a9b319bbf7.png)

I'm not completely adverse to you using Plastic for inspiration, in fact I'm flattered, but don't assume you can't design. Invest in Affinity Designer (from you screenshots, I presume you have a Mac), and you'll quickly learn to play with and combine shapes to great effect. Master the snapping tool, everything lines-up automatically and immediately looks professional.

**Comment by rafamel** [comment]
Hi Will, thanks for taking the time to give such a thorough recommendation! I'll definitely check out Affinity Designer in the future - it sounds great, - though right now it's not a priority for me as I'm time-wisely barely able to get some of the coding projects forward. I really appreciate the recommendation, so I'll look it up in the incoming months for sure. I can create a new logo for this project or leave it logo-less for a bit if the current is an issue at all for you. Or I can try to modify the color palette. Just let me know, if it makes you the tiniest bit uncomfortable I'll scrap it ;)

Thanks again, Will.
Rafa
